package com.ncr.storage.config.spring;

import com.google.api.gax.core.CredentialsProvider;
import com.google.cloud.storage.Bucket;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.IOException;

@Configuration
public class GCPConfig {

    @Value("${gcp.storage.bucket.name}")
    private String bucketName;

    @Bean
    public Storage getStorage(CredentialsProvider credentialsProvider) throws IOException {
        return StorageOptions.newBuilder().setCredentials(credentialsProvider.getCredentials()).build().getService();
    }

    /**
     * CredentialsProvider is auto-generated by spring using the application properties credentials location.
     * @param credentialsProvider
     * @return
     * @throws IOException
     */
    @Bean
    public Bucket getBucket(CredentialsProvider credentialsProvider) throws IOException {
        return getStorage(credentialsProvider).get(bucketName);
    }
}
